### ISSUE TITLE
Implementation story book

### ISSUE THREAD

**Issue by truongdn-it** [truongdn-it/nextjs-boilerplate#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vansu99** [comment]
Hi @truongdn-it bro, I did it. Please check the pull request.

https://github.com/truongdn-it/nextjs-boilerplate/pull/16

**Comment by truongdn-it** [comment]
> Hi @truongdn-it bro, I did it. Please check the pull request.
> 
> #16

Hi @vansu99,

Thank you for hard working!!!

I merged.
